import "../scss/app.scss";
import "../img/samsung_logo.png";
import "../img/hp_logo.png";
import "../img/lenovo-logo.png";
import "../img/sony-logo.png";
import "../img/acer-logo.png";
import "../img/news1.png";
import "../img/news2.png";
import "../img/news3.png";
import "../img/news4.png";
import '../img/banner.png';
import '../img/instagram.png';
import '../img/product1.png'
import '../img/product2.png'
import '../img/product3.png'
import '../img/product4.png'
import '../img/product5.png'
import '../img/product6.png'
import '../img/keyboards.png'
import '../img/mouse.png';
import '../img/laptop.png';
import '../img/steering-wheel.png';
import '../img/video-card.png';
import '../img/monitor.png';
import '../img/avatar.png';
import '../img/inst_1.png';
import '../img/inst_2.png';
import '../img/inst_3.png';

//svg
import "../svg/hamburger1.svg";
import "../svg/assembly.svg";
import "../svg/auth.svg";
import "../svg/cart.svg";
import "../svg/compare.svg";
import "../svg/favorite.svg";
import "../svg/logo.svg";
import "../svg/search.svg";
import "../svg/catalog_button.svg";
import "../svg/mastercard.svg";
import "../svg/visa.svg";
import "../svg/11_years.svg";
import "../svg/best_price.svg";
import "../svg/delivery.svg";
import "../svg/manager.svg";
import "../svg/mortage.svg";
import "../svg/warranty.svg";
import '../svg/colored_star.svg';
import '../svg/arrow-left.svg';
import '../svg/arrow-right.svg';
import '../svg/empty_star.svg';
import '../svg/vertical_line.svg';
import '../svg/down-arrow.svg';
import '../svg/header_line.svg';
import '../svg/processor.svg';
import '../svg/categories_arrow.svg';
import '../svg/computer.svg';
import '../svg/console.svg';
import '../svg/laptop.svg';
import '../svg/laptop_component.svg';
import '../svg/monitor.svg';
import '../svg/printer.svg';
import '../svg/speakers.svg';
import '../svg/tablet.svg';
import '../svg/web_staff.svg';

