import "../scss/app.scss";
import "../img/samsung_logo.png";
import "../img/hp_logo.png";
import "../img/lenovo-logo.png";
import "../img/sony-logo.png";
import "../img/acer-logo.png";
import "../img/news1.png";
import "../img/news2.png";
import "../img/news3.png";
import "../img/news4.png";
import '../img/banner.jpg';
import '../img/top_banner.png';
import '../img/instagram.png';
import "../svg/hamburger1.svg";
import "../svg/icon.svg";
import "../svg/auth.svg";
import "../svg/cart.svg";
import "../svg/compare.svg";
import "../svg/favorite.svg";
import "../svg/logo.svg";
import "../svg/search.svg";
import "../svg/catalog_button.svg";
/*
import "../img/acer-logo.png";
import "../img/acer-logo.png";
import "../img/acer-logo.png";*/
